apiVersion: apps/v1
kind: Deployment 
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata: 
      labels: 
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "postgres"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data/pgdata
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1  # ← 맨 위로!
kind: Service
metadata:
  name: coding404-postgres
spec:
  selector:
    app: postgres
  ports:
  - name: dbport
    port: 5432
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # storageClassName: mylocalstorage  # GKE Autopilot 기본 스토리지 클래스 사용
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-storage
# spec:
#   storageClassName: mylocalstorage
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/some/new/mydata
#     type: DirectoryOrCreate
# apiVersion: apps/v1
# kind: Deployment 
# metadata:
#   name: postgres
# spec:
#   selector:
#     matchLabels:
#       app: postgres
#   replicas: 1
#   template:
#     metadata: 
#       labels: 
#         app: postgres
#     spec:
#       containers:
#       - name: postgres
#         image: postgres:14
#         env:
#         - name: POSTGRES_USER
#           value: "postgres"
#         - name: POSTGRES_PASSWORD
#           value: "1234"
#         - name: POSTGRES_DB
#           value: "postgres"
#         - name: PGDATA
#           value: "/var/lib/postgresql/data/pgdata"
#         volumeMounts:  # ← 이 부분이 컨테이너 안으로 들어와야 함
#         - name: postgres-persistent-storage
#           mountPath: /var/lib/postgresql/data/pgdata
#       volumes:
#       - name: postgres-persistent-storage
#         persistentvolumeClaim :
#           claimName: postgres-pvc
#         # hostPath:  # ← 대문자 P
#         #   path: /mnt/some/mydata
#         #   type: DirectoryOrCreate

# ---
# apiVersion: v1  # ← apiVersion을 위로 올리는 게 일반적
# kind: Service
# metadata:
#   name: coding404-postgres
# spec:
#   selector:
#     app: postgres
#   ports:
#   - name: dbport
#     port: 5432
#   type: ClusterIP
