apiVersion: apps/v1 # 큐에 대한 롤링배포
kind: Deployment 
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres

  replicas: 1 # 몇 개의 Pod 인스턴스를 유지할지
  template: # Pod의 템플릿을 정의
    metadata: 
      labels: 
        app: postgres

    spec:
      containers:
      - name: postgres
        image: postgres:14 # 포스트그레 공식 도커 이미지
        env:
        - name: POSTGRES_USER  # 초기슈퍼사용자 유저명
          value: "postgres"
        - name: POSTGRES_PASSWORD  # 비밀번호
          value: "1234"
        - name: POSTGRES_DB  # 기본 데이터베이스 이름
          value: "postgres"
        - name: PGDATA  # 데이터 저장 경로 (선택적)
          value: "/var/lib/postgresql/data/pgdata"

--- # 데이터베이스 서비스
kind: Service
apiVersion: v1
metadata:
  name: coding404-postgres #이름은 실제 position-tracker에서 접속하는 이름이므로 매우 중요합니다.

spec:
  selector:
    app: postgres
  ports:
    - name: dbport
      port: 5432
  type: ClusterIP # 외부에서 접속 가능하지 않습니다