apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # storageClassName: mylocalstorage # GKE Autopilot 기본 스토리지 클래스 사용
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: local-storage
# spec:
#   storageClassName: mylocalstorage
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /mnt/some/new/mydata
#     type: DirectoryOrCreate
