apiVersion: v1
kind: Pod
metadata:
  name: webapp # 프로젝트명칭 이름
  labels:
    app: webapp 
    release: "0" # 버전명 추가
spec:
  containers: 
  - name: webapp 
    image: coding404/k8s-coding404-webapp-react:v0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-v-0-1 # 프로젝트명칭 변경
  labels:
    app: webapp 
    release: "0-1" # 버전명 추가
spec:
  containers: 
  - name: webapp 
    image: coding404/k8s-coding404-webapp-react:v0-1 # 버전변경