apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:14 # 포스트그레 공식 도커 이미지
    env:
    - name: POSTGRES_USER  # 초기슈퍼사용자 유저명
      value: "postgres"
    - name: POSTGRES_PASSWORD  # 비밀번호
      value: "1234"
    - name: POSTGRES_DB  # 기본 데이터베이스 이름
      value: "postgres"
    - name: PGDATA  # 데이터 저장 경로 (선택적)
      value: "/var/lib/postgresql/data/pgdata"
--- 
kind: Service
apiVersion: v1
metadata:
  name: database-postgres
spec:
  selector:
    app: postgres # 메타데이터의 label값
  ports:
    - name: dbport
      port: 5432
      nodePort: 30020
  # type: ClusterIP # 외부에서는 볼 수 없고, 내부에서 다른 pod가 참조할 수 있도록 함
  type: NodePort # 외부에서 개방